package com.lambda.foodtrucktrackr.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;

@Entity
@Table(name = "menuitemphotos")
@ApiModel(value = "MenuItemPhoto", description = "A photo of a menu item")
public class MenuItemPhoto extends Auditable {
    @ApiModelProperty(name = "menu item photo id", value = "primary key for MenuItemPhoto (automatically generated by database", example = "31")
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long menuitemphotoid;

    @ApiModelProperty(name = "image URL", value = "the url of the image of this menu item", required = true)
    @Column(nullable = false)
    private String imageurl;

    @ManyToOne
    @JoinColumn(name = "menuitemid")
    @JsonIgnoreProperties(value = "menuitemphotos", allowSetters = true)
    private MenuItem menuitem;

    public MenuItemPhoto() {
    }

    public MenuItemPhoto(String imageurl) {
        this.imageurl = imageurl;
    }

    public long getMenuitemphotoid() {
        return menuitemphotoid;
    }

    public void setMenuitemphotoid(long menuitemphotoid) {
        this.menuitemphotoid = menuitemphotoid;
    }

    public String getImageurl() {
        return imageurl;
    }

    public void setImageurl(String imageurl) {
        this.imageurl = imageurl;
    }

    public MenuItem getMenuitem() {
        return menuitem;
    }

    public void setMenuitem(MenuItem menuitem) {
        this.menuitem = menuitem;
    }
}
