package com.lambda.foodtrucktrackr.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "trucks")
@ApiModel(value = "Truck", description = "A food truck")
public class Truck {
    @ApiModelProperty(name = "truck id", value = "primary key for truck (automatically generated by database)", example = "1")
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long truckid;

    @ApiModelProperty(name = "truck name", value = "the name of the food truck", example = "Lunch Box", required = true)
    @Column(nullable = false)
    private String truckname;

    @ApiModelProperty(name = "cuisine type", value = "the kind of food served by this truck", example = "Salvadoran")
    private String cuisinetype;

    @OneToMany(mappedBy = "truck", cascade = CascadeType.ALL, orphanRemoval = true)
    @JsonIgnoreProperties(value = "truck", allowSetters = true)
    private List<Menu> menus = new ArrayList<>();


}
