package com.lambda.foodtrucktrackr.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "trucks")
@ApiModel(value = "Truck", description = "A food truck")
public class Truck extends Auditable {
    @ApiModelProperty(name = "truck id", value = "primary key for Truck (automatically generated by database)", example = "17")
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long truckid;

    @ApiModelProperty(name = "truck name", value = "the name of the food truck", example = "Lunch Box", required = true)
    @Column(nullable = false)
    private String truckname;

    @ApiModelProperty(name = "cuisine type", value = "the kind of food served by this truck", example = "Salvadoran")
    private String cuisinetype;

    @OneToMany(mappedBy = "truck", cascade = CascadeType.ALL, orphanRemoval = true)
    @JsonIgnoreProperties(value = "truck", allowSetters = true)
    private List<Menu> menus = new ArrayList<>();

    @OneToMany(mappedBy = "truck", cascade = CascadeType.ALL, orphanRemoval = true)
    @JsonIgnoreProperties(value = "truck", allowSetters = true)
    private List<UserTrucks> users = new ArrayList<>();

    public Truck() {
    }

    public Truck(String truckname, String cuisinetype) {
        this.truckname = truckname;
        this.cuisinetype = cuisinetype;
    }

    public long getTruckid() {
        return truckid;
    }

    public void setTruckid(long truckid) {
        this.truckid = truckid;
    }

    public String getTruckname() {
        return truckname;
    }

    public void setTruckname(String truckname) {
        this.truckname = truckname;
    }

    public String getCuisinetype() {
        return cuisinetype;
    }

    public void setCuisinetype(String cuisinetype) {
        this.cuisinetype = cuisinetype;
    }

    public List<Menu> getMenus() {
        return menus;
    }

    public void setMenus(List<Menu> menus) {
        this.menus = menus;
    }

    public List<UserTrucks> getUsers() {
        return users;
    }

    public void setUsers(List<UserTrucks> users) {
        this.users = users;
    }
}
